### ISSUE TITLE
Создать сервис по работе с файловой системой

### ISSUE THREAD

**Issue by SShliakhin** [djud17-org/SB-MDEditor#26]
В Theme константа - ссылка на корень файловой системы в Bandle

Имеет следующие функции
1. Манипуляции с URL файла - формирование, разбивка на части
2. Выдача списка файлов по переданному URL
3. Выдача содержимого файла
4. Выдача свойств файла

**Comment by djud17** [comment]
@SShliakhin разъясни пожалуйста некоторые моменты:
1. По первому пункту, что за манипуляции и для чего это?
2. По последнему пункту, какие свойства имеются в виду?

**Comment by SShliakhin** [comment]
@djud17 Это первичное видение - кажется уже не актуально, все перекрывается моделькой File от Кирилла (твои 1 и 2), а пункт 2 (из начального тикета) закрыт другим сервисом

**Comment by djud17** [comment]
Понял, то есть мне нужно реализовать 2 функции в этом сервисе, верно?
Выдача содержимого файла
Выдача свойств файла

В Models, нет модели File, в проекте тоже не нахожу

**Comment by SShliakhin** [comment]
с пунктом 2 я погоричился - нужно (спутал с недавно открытыми)
В Models, нет модели File, в проекте тоже не нахожу - конечно нет, возьми у Кирилла или лучше у Антона в ветке по модулю Открыть файл, который еще не затощили. Здесь уже проблема синхронизации задач будет.
