### ISSUE TITLE
Cоздать файл about.md

### ISSUE THREAD

**Issue by SShliakhin** [djud17-org/SB-MDEditor#4]
Файл about.md  - описание приложения и участников команды, которая над ним трудилась.

- [x] файл создан и лежит в корне assets (на подумать: или в папке About?)

**Comment by chuRealOff** [comment]
Разместил файл в одноименной папке проекта - "About"

**Comment by SShliakhin** [comment]
В Assets папке в любом случае должен лежать! Вопрос был, нужна ли доп папочка)
